InteriorDesignStudio/Models/Domain/Project.cs
namespace InteriorDesignStudio.Models.Domain
{
    public class Project
    {
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public DateTime CreationDate { get; set; }
        public string Description { get; set; }
        public string ImagePath { get; set; }
        public int UserID { get; set; }
        public User User { get; set; }
        public ICollection<Comment>? Comments { get; set; }
    }
}

InteriorDesignStudio/Controllers/CommentController.cs
using InteriorDesignStudio.Models.Domain;
using InteriorDesignStudio.Repository.Interfaces;
using InteriorDesignStudio.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace InteriorDesignStudio.Controllers
{
    public class CommentController : Controller
    {
        private readonly ICommentRepository _commentRepository;
        private readonly IProjectRepository _projectRepository;
        private readonly IUserRepository _userRepository;
        public CommentController(ICommentRepository commentRepository, IProjectRepository projectRepository, IUserRepository userRepository)
        {
            _commentRepository = commentRepository;
            _projectRepository = projectRepository;
            _userRepository = userRepository;
        }

        [HttpGet]
        [Authorize]
        [Route("/comment/create/{projectId}")]
        public async Task<IActionResult> Create(int projectId)
        {
            var project = await _projectRepository.GetProjectByIdAsync(projectId);

            if (project == null)
            {
                return RedirectToAction("Index", "Project");
            }

            var viewModel = new CommentCreateViewModel
            {
                ProjectID = projectId
            };

            return View(viewModel);
        }

        [HttpPost]
        [Authorize]
        [Route("/comment/create/{projectId}")]
        public async Task<IActionResult> Create(int projectId, CommentCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var comment = new Comment
                {
                    CommentText = viewModel.CommentText,
                    CreationDate = DateTime.Now,
                    UserID = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)),
                    ProjectID = projectId
                };

                await _commentRepository.AddCommentAsync(comment);

                return RedirectToAction("Details", "Project", new { id = projectId });
            }

            return View(viewModel);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var comment = await _commentRepository.GetCommentByIdAsync(id);
            var user = await _userRepository.GetUserByIdAsync(comment.UserID);
            if (user == null)
            {
                return RedirectToAction("Index", "Project");
            }

            if(user.UserID != comment.UserID)
            {
                return RedirectToAction("Index", "Project");
            }

            if(comment == null)
            {
                return RedirectToAction("Index", "Project");
            }
            var viewModel = new CommentViewModel
            {
                CommentId = comment.CommentID,
                CommentText = comment.CommentText,
            };
            return View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> DeletePost(int commentId)
        {
            var comment = await _commentRepository.GetCommentByIdAsync(commentId);
            var user = await _userRepository.GetUserByIdAsync(comment.UserID);
            if (user == null)
            {
                return RedirectToAction("Index", "Project");
            }

            if (user.UserID != comment.UserID)
            {
                return RedirectToAction("Index", "Project");
            }

            await _commentRepository.DeleteCommentAsync(commentId);

            return RedirectToAction("Index", "Project");
        }
    }
}

InteriorDesignStudio/Controllers/ProjectController.cs
using InteriorDesignStudio.Models.Domain;
using InteriorDesignStudio.Repository.Interfaces;
using InteriorDesignStudio.Utils;
using InteriorDesignStudio.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace InteriorDesignStudio.Controllers
{
    public class ProjectController : Controller
    {
        private readonly IProjectRepository _projectRepository;
        private readonly IUserRepository _userRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProjectController(IProjectRepository projectRepository, IWebHostEnvironment webHostEnvironment, IUserRepository userRepository)
        {
            _projectRepository = projectRepository;
            _webHostEnvironment = webHostEnvironment;
            _userRepository = userRepository;
        }
        public async Task<IActionResult> Index()
        {
            var projects = await _projectRepository.GetAllProjectsAsync();
            return View(projects);
        }
        public async Task<IActionResult> Details(int id)
        {
            var project = await _projectRepository.GetProjectByIdAsync(id);

            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(ProjectCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                if (viewModel.ImageData != null && viewModel.ImageData.Length > 0)
                {
                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(viewModel.ImageData.FileName);

                    var filePath = Path.Combine(_webHostEnvironment.WebRootPath, "uploads", fileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await viewModel.ImageData.CopyToAsync(stream);
                    }
                    var project = new Project
                    {
                        ProjectName = viewModel.ProjectName,
                        CreationDate = viewModel.CreationDate,
                        Description = viewModel.Description,
                        UserID = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)),

                        ImagePath = "/uploads/" + fileName,
                    };

                    await _projectRepository.AddProjectAsync(project);
                }

                return RedirectToAction("Index", "Project");
            }

            return View(viewModel);
        }
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var project = await _projectRepository.GetProjectByIdAsync(id);

            if(project.UserID != int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)))
            {
                return RedirectToAction("Index");
            }

            if (project == null)
            {
                return NotFound();
            }

            var viewModel = new ProjectEditViewModel
            {
                ProjectID = project.ProjectID,
                ProjectName = project.ProjectName,
                CreationDate = project.CreationDate,
                Description = project.Description,
                UserID = project.UserID
            };


            return View(viewModel);
        }
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(ProjectEditViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var existingProject = await _projectRepository.GetProjectByIdAsync(viewModel.ProjectID);

                if (existingProject == null)
                {
                    return NotFound();
                }

                existingProject.ProjectName = viewModel.ProjectName;
                existingProject.CreationDate = viewModel.CreationDate;
                existingProject.Description = viewModel.Description;
                existingProject.UserID = viewModel.UserID;

                await _projectRepository.UpdateProjectAsync(existingProject);

                return RedirectToAction("Index");
            }

            return View(viewModel);
        }
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var project = await _projectRepository.GetProjectByIdAsync(id);

            if (project == null)
            {
                return NotFound();
            }

            if (project.UserID != int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)))
            {
                return RedirectToAction("Index","Project");
            }

            var viewModel = new ProjectDeleteViewModel
            {
                ProjectID = project.ProjectID,
                ProjectName = project.ProjectName,
                CreationDate = project.CreationDate,
                Description = project.Description,
                ImagePath = project.ImagePath,
                UserID = project.UserID
            };

            return View(viewModel);
        }
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(ProjectDeleteViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var existingProject = await _projectRepository.GetProjectByIdAsync(viewModel.ProjectID);

                if (existingProject == null)
                {
                    return NotFound();
                }

                var user = await _userRepository.GetUserByIdAsync(existingProject.UserID);

                if (user == null || !PasswordHasher.VerifyPassword(viewModel.Password, user.Password))
                {
                    ModelState.AddModelError("Password", "Invalid password");
                    return View(viewModel);
                }

                await _projectRepository.DeleteProjectAsync(viewModel.ProjectID);

                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

    }
}

InteriorDesignStudio/Views/Project/Create.cshtml
@model InteriorDesignStudio.ViewModels.ProjectCreateViewModel

<h2 class="text-center">Create Project</h2>

<div class="container">
    <div class="card">
        <div class="card-body">
            <form asp-action="Create" method="post" enctype="multipart/form-data">

                <div class="mb-3">
                    <label for="ProjectName" class="form-label">Project Name</label>
                    <input asp-for="ProjectName" class="form-control" id="ProjectName" />
                    <span asp-validation-for="ProjectName" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label for="CreationDate" class="form-label">Creation Date</label>
                    <input asp-for="CreationDate" type="date" class="form-control" id="CreationDate" />
                    <span asp-validation-for="CreationDate" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label for="Description" class="form-label">Description</label>
                    <textarea asp-for="Description" class="form-control" id="Description" rows="4"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label for="ImageData" class="form-label">Image Data</label>
                    <input asp-for="ImageData" type="file" class="form-control" id="ImageData" />
                    <span asp-validation-for="ImageData" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Create Project</button>
                </div>

            </form>
        </div>
    </div>
</div>

InteriorDesignStudio/Views/Project/Delete.cshtml
@model InteriorDesignStudio.ViewModels.ProjectDeleteViewModel

<h2 class="text-center">Delete Project</h2>

<div class="container">
    <div class="card">
        <div class="card-body">

            <form asp-action="Delete" method="post">

                <input type="hidden" asp-for="ProjectID" />
                <input type="hidden" asp-for="UserID" />

                <div class="mb-3 text-center">
                    <img src="@Model.ImagePath" alt="Project Image" class="img-fluid mx-auto" />
                </div>

                <div class="mb-3">
                    <label class="form-label">Project Name</label>
                    <p class="form-control">@Model.ProjectName</p>
                </div>

                <div class="mb-3">
                    <label class="form-label">Creation Date</label>
                    <p class="form-control">@Model.CreationDate.ToShortDateString()</p>
                </div>

                <div class="mb-3">
                    <label class="form-label">Description</label>
                    <p class="form-control">@Model.Description</p>
                </div>

                <div class="mb-3">
                    <label class="form-label">Enter Your Password</label>
                    <input asp-for="Password" type="password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <button type="submit" class="btn btn-danger">Delete Project</button>
                </div>

            </form>

        </div>
    </div>
</div>

InteriorDesignStudio/Views/Project/Details.cshtml
@model InteriorDesignStudio.Models.Domain.Project
@using System.Security.Claims


<style>
    .project-details {
        margin-top: 20px;
    }

    .project-image {
        width: 100%;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .project-info {
        margin-top: 20px;
    }

    .comments-section {
        margin-top: 30px;
    }

    .comment-list {
        list-style: none;
        padding: 0;
    }

    .comment-item {
        border-bottom: 1px solid #ddd;
        padding: 10px 0;
    }

    .comment-user {
        font-weight: bold;
    }

    .related-projects {
        margin-top: 30px;
    }

    .related-project-item {
        margin-bottom: 20px;
    }
</style>

<div class="container project-details">

    <h1 class="my-4">
        @Model.ProjectName
    </h1>

    <div class="row">

        <div class="col-md-8">
            <img class="img-fluid project-image" src="@Model.ImagePath" alt="Project Image">
        </div>

        <div class="col-md-4 project-info">
            <h3 class="my-3">Project Description</h3>
            <p>@Model.Description</p>
            <h3 class="my-3">Project Details</h3>
            <ul>
                <li>Creation Date: @Model.CreationDate.ToShortDateString()</li>
                <li>User: @Model.User.Name @Model.User.Surname</li>
                <li>Email: @Model.User.Email</li>
            </ul>
        </div>

    </div>

    <div class="row comments-section">
        <div class="col-md-12">
            <h3 class="my-3">Comments:</h3>
            @if (Model.Comments != null && Model.Comments.Any())
            {
                <ul class="comment-list">
                    @foreach (var comment in Model.Comments)
                    {
                        <div class="card mb-3">
                            <div class="card-body">
                                <div class="d-flex flex-start">
                                    <img class="rounded-circle shadow-1-strong me-3"
                                         src="https://cdn-icons-png.flaticon.com/512/149/149071.png" alt="avatar" width="40"
                                         height="40" />
                                    <div class="w-100">
                                        <div class="d-flex justify-content-between align-items-center mb-3">
                                            <h6 class="text-primary fw-bold mb-0">
                                                @comment.User.Name @comment.User.Surname
                                                <span class="text-dark ms-2">@comment.CommentText</span>
                                            </h6>
                                            <p class="mb-0">@comment.CreationDate.ToShortDateString()</p>
                                        </div>
                                        <div class="d-flex justify-content-between align-items-center">
                                            <p class="small mb-0" style="color: #aaa;">
                                                @if (comment.UserID == int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)))
                                                {
                                                    <a asp-controller="Comment" asp-action="Delete" asp-route-Id="@comment.CommentID" class="link-grey">Remove</a>

                                                }
                                            </p>
                                            <div class="d-flex flex-row">
                                                <i class="fas fa-star text-warning me-2"></i>
                                                <i class="far fa-check-circle" style="color: #aaa;"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    }
                </ul>
            }
            else
            {
                <p>No comments available.</p>
            }
            <a asp-controller="Comment" asp-action="Create" asp-route-projectId="@Model.ProjectID" class="btn btn-primary">Add a Comment</a>
        </div>
    </div>
</div>

InteriorDesignStudio/Views/Project/Edit.cshtml
@model InteriorDesignStudio.ViewModels.ProjectEditViewModel

<h2 class="text-center">Edit Project</h2>

<div class="container">
    <div class="card">
        <div class="card-body">

            <form asp-action="Edit" method="post">

                <input type="hidden" asp-for="ProjectID" />

                <div class="mb-3">
                    <label class="form-label">Project Name</label>
                    <input asp-for="ProjectName" class="form-control" />
                    <span asp-validation-for="ProjectName" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label">Creation Date</label>
                    <input asp-for="CreationDate" type="date" class="form-control" />
                    <span asp-validation-for="CreationDate" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label">Description</label>
                    <textarea asp-for="Description" class="form-control" rows="4"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <input asp-for="UserID" hidden class="form-control" />
                </div>

                <div class="mb-3 text-center">
                    <button type="submit" class="btn btn-primary">Update Project</button>
                </div>

            </form>

        </div>
    </div>
</div>

InteriorDesignStudio/Views/Project/Index.cshtml
@model IEnumerable<InteriorDesignStudio.Models.Domain.Project>
@using System.Security.Claims

<div class="container">
    <div class="d-flex justify-content-between align-items-center">
        <h2>All Projects</h2>

        @if (User.FindFirstValue(ClaimTypes.Role) == "Admin")
        {
            <a href="@Url.Action("Create", "Project")" class="btn btn-primary">Add Project</a>
        }
    </div>
    <div class="row">
        @foreach (var project in Model)
        {
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="@project.ImagePath" alt="Project Image">
                    <div class="card-body">
                        <h5 class="card-title">@project.ProjectName</h5>
                        <p class="card-text">@project.Description</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="@Url.Action("Details", new { id = project.ProjectID })" class="btn btn-sm btn-outline-secondary">View Details</a>
                                @if (User.FindFirstValue(ClaimTypes.Role) == "Admin")
                                {
                                    <a href="@Url.Action("Edit", "Project", new { id = project.ProjectID })" class="btn btn-sm btn-outline-secondary">Edit</a>
                                    <a href="@Url.Action("Delete", "Project", new { id = project.ProjectID })" class="btn btn-sm btn-outline-danger">Delete</a>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>