InteriorDesignStudio/Controllers/OrderController.cs
using InteriorDesignStudio.Models.Domain;
using InteriorDesignStudio.Repository.Interfaces;
using InteriorDesignStudio.Utils;
using InteriorDesignStudio.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;

namespace InteriorDesignStudio.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly IServiceRepository _serviceRepository;
        private readonly IUserRepository _userRepository;
        private readonly IWorkflowStageRepository _workflowStageRepository;
        public OrderController(IOrderRepository orderRepository, IServiceRepository serviceRepository, IUserRepository userRepository, IWorkflowStageRepository workflowStageRepository)
        {
            _orderRepository = orderRepository;
            _serviceRepository = serviceRepository;
            _userRepository = userRepository;    
            _workflowStageRepository = workflowStageRepository;
        }
        [Authorize(Roles = "Designer,Admin")]
        public async Task<IActionResult> Index()
        {
            var orders = await _orderRepository.GetAllOrdersAsync();
            return View(orders);
        }
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Create()
        {
            var services = await _serviceRepository.GetAllServicesAsync();
            var serviceOptions = services.Select(s => new SelectListItem
            {
                Value = s.ServiceID.ToString(),
                Text = s.ServiceName
            });

            var viewModel = new OrderCreateViewModel
            {
                ServiceOptions = serviceOptions
            };

            return View(viewModel);
        }
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(OrderCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var order = new Order
                {
                    ProjectName = viewModel.ProjectName,
                    Description = viewModel.Description,
                    OrderDate = DateTime.Now, 
                    UserID = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)),
                    ServiceID = viewModel.SelectedServiceID, 
                    StageID = 1
                };

                await _orderRepository.AddOrderAsync(order);

                return RedirectToAction("Profile","Account");
            }

            return View(viewModel);
        }
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var order = await _orderRepository.GetOrderByIdAsync(id);
            var user = await _userRepository.GetUserByIdAsync(int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)));

            if (order == null)
            {
                return NotFound();
            }

            if(user == null)
            {
                return NotFound();
            }

            if(user.UserID != order.UserID)
            {
                return RedirectToAction("Profile", "Account");
            }

            var services = await _serviceRepository.GetAllServicesAsync();
            var serviceOptions = services.Select(s => new SelectListItem
            {
                Value = s.ServiceID.ToString(),
                Text = s.ServiceName,
                Selected = s.ServiceID == order.ServiceID
            });

            var viewModel = new OrderUpdateViewModel
            {
                OrderID = order.OrderID,
                ProjectName = order.ProjectName,
                Description = order.Description,
                SelectedServiceID = order.ServiceID,
                ServiceOptions = serviceOptions
            };

            return View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(OrderUpdateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var order = await _orderRepository.GetOrderByIdAsync(viewModel.OrderID);

                if (order == null)
                {
                    return NotFound();
                }

                order.ProjectName = viewModel.ProjectName;
                order.Description = viewModel.Description;
                order.ServiceID = viewModel.SelectedServiceID;

                await _orderRepository.UpdateOrderAsync(order);

                return RedirectToAction("Profile", "Account");
            }

            return View(viewModel);
        }
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> ConfirmDelete(int id)
        {
            var order = await _orderRepository.GetOrderByIdAsync(id);
            var user = await _userRepository.GetUserByIdAsync(int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)));

            if (user == null)
            { 
                return NotFound(); 
            }

            if (order == null)
            {
                return RedirectToAction("Profile", "Account");
            }

            if(user.UserID != order.UserID)
            {
                return RedirectToAction("Profile", "Account");
            }

            var viewModel = new OrderConfirmDeleteViewModel
            {
                OrderID = order.OrderID,
                ProjectName = order.ProjectName,
                Description = order.Description
            };

            return View(viewModel);
        }
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Delete(int id, OrderConfirmDeleteViewModel viewModel)
        {
            var user = await _userRepository.GetUserByIdAsync(int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)));
            if (user == null)
            {
                return RedirectToAction("Profile", "Account");
            }

            if(PasswordHasher.VerifyPassword(viewModel.Password, user.Password))
            {
                try
                {
                    await _orderRepository.DeleteOrderAsync(id);
                    return RedirectToAction("Profile", "Account");
                }
                catch (Exception ex)
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            return RedirectToAction("Profile", "Account");
        }
        [HttpGet]
        [Authorize(Roles = "Designer,Admin")]
        public async Task<IActionResult> ChangeStatus(int id)
        {
            var order = await _orderRepository.GetOrderByIdAsync(id);
            var workflowStage = await _workflowStageRepository.GetAllStagesAsync();

            if (order == null)
            {
                return NotFound();
            }

            var serviceOptions = workflowStage.Select(wf => new SelectListItem
            {
                Value = wf.StageID.ToString(),
                Text = wf.StageName,
                Selected = wf.StageID == order.StageID
            });

            var viewModel = new OrderChangeStatusViewModel
            {
                OrderID = order.OrderID,
                ProjectName = order.ProjectName,
                Description = order.Description,
                StageOptions = serviceOptions,
            };

            return View(viewModel);
        }
        [HttpPost]
        public async Task<IActionResult> ChangeStatus(OrderChangeStatusViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var order = await _orderRepository.GetOrderByIdAsync(viewModel.OrderID);

                if (order == null)
                {
                    return NotFound();
                }

                order.StageID = viewModel.SelectedStageID;

                await _orderRepository.UpdateOrderAsync(order);

                return RedirectToAction("Index", "Home");
            }

            return View(viewModel);
        }
    }
}

InteriorDesignStudio/Controllers/ServiceController.cs
using InteriorDesignStudio.Models.Domain;
using InteriorDesignStudio.Repository.Interfaces;
using InteriorDesignStudio.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InteriorDesignStudio.Controllers
{
    public class ServiceController : Controller
    {
        private readonly IServiceRepository _serviceRepository;

        public ServiceController(IServiceRepository serviceRepository)
        {
            _serviceRepository = serviceRepository;
        }

        public async Task<IActionResult> Index()
        {
            var services = await _serviceRepository.GetAllServicesAsync();

            if (services != null && services.Any())
            {
                return View(services);
            }
            else
            {
                ViewBag.Message = "No services available.";
                return View();
            }
        }

        [HttpGet]
        [Authorize(Roles = "Designer,Admin")]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ServiceCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var service = new Service
                {
                    ServiceName = viewModel.ServiceName,
                    Description = viewModel.Description,
                    Cost = viewModel.Cost
                };

                await _serviceRepository.AddServiceAsync(service);
                return RedirectToAction("Index");
            }

            return View(viewModel);
        }
        [HttpGet]
        [Authorize(Roles = "Designer,Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var service = await _serviceRepository.GetServiceByIdAsync(id);

            if (service == null)
            {
                return NotFound(); 
            }

            var viewModel = new ServiceEditViewModel
            {
                ServiceID = service.ServiceID,
                ServiceName = service.ServiceName,
                Description = service.Description,
                Cost = service.Cost
            };

            return View(viewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(ServiceEditViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var service = new Service
                {
                    ServiceID = viewModel.ServiceID,
                    ServiceName = viewModel.ServiceName,
                    Description = viewModel.Description,
                    Cost = viewModel.Cost
                };

                await _serviceRepository.UpdateServiceAsync(service);
                return RedirectToAction("Index");
            }

            return View(viewModel);
        }
        [HttpGet]
        [Authorize(Roles = "Designer,Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var service = await _serviceRepository.GetServiceByIdAsync(id);

            if (service == null)
            {
                return NotFound();
            }

            var viewModel = new ServiceDeleteViewModel
            {
                ServiceID = service.ServiceID,
                ServiceName = service.ServiceName,
                Description = service.Description,
                Cost = service.Cost
            };

            return View(viewModel);
        }
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Designer,Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _serviceRepository.DeleteServiceAsync(id);
            return RedirectToAction("Index");
        }
    }
}

InteriorDesignStudio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InteriorDesignStudio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InteriorDesignStudio.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InteriorDesignStudio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Index">Projects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Service" asp-action="Index">Services</a>
                        </li>
                    </ul>

                    <div class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <a class="nav-link btn btn-primary text-white mr-2" asp-area="" asp-controller="Account" asp-action="Profile">Profile</a>
                            <a class="nav-link btn btn-success text-white mr-2" asp-area="" asp-controller="Order" asp-action="Create">Create Order</a>
                        }
                        else
                        {
                            <a class="nav-link text-dark mr-2" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            <a class="nav-link text-dark mr-2" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        }
                    </div>

                </div>
            </div>
        </nav>

    </header>
    <div class="container">
    </div>
    <main role="main">
        @RenderBody()
    </main>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - InteriorDesignStudio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>